### PR TITLE
Fix README formatting

### PR DESCRIPTION
**Pull request by armilam**
There was a hidden character that messed up the formatting for a block of code in the README.

Also, this removes some trailing whitespace - my editor does that automatically.

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Any "2 spaces" after a text line (while not inside a code block) is for formatting (line break)
Please add them back
Otherwise this PR is good

**Comment by armilam** [comment]
Sorry for the long turn around time. I have restored the trailing whitespace. Now I believe this puts the README in a better state.

**Comment by PikachuEXE** [comment]
Now I think this is a duplicate of #391 
What do you think?

**Comment by armilam** [comment]
Yep, you are exactly right. Looks like I took too long! Closing this PR.

**Pull request closed without merging**
