### PR TITLE
Allow Custom assets to be cached (from webpack like tools)

### PR DESCRIPTION
**Pull request by sairam**
We are using webpack to generate assets. 

I have written a rake task to allow merging of custom assets into the manifest file.
Uploading works too, but the only blocker was we these assets are not being marked as cached on s3. 

This is a PR to allow custom regexp match to allow setting Cache headers.

### CODE REVIEW

**Comment by PikachuEXE** [comment]
- I think it's better to rename `cache_asset_regexp` => `cache_asset_regexps`, it expects >1 regexp
- Also having a setter to wrap singular value input into array might be good
- Also please update doc, unmentioned feature is not good

**Comment by sairam** [comment]
Should I add them the config in the generators too? (rb and yml)

**Comment by PikachuEXE** [comment]
Sure! I forgot those

**Comment by sairam** [comment]
Documented features and updated code as per suggestions.

**Comment by PikachuEXE** [comment]
Thanks!
Will release this soon, next week or the week after

**Comment by PikachuEXE** [comment]
Released with 2.1.0

**Pull request merged**
