### PR TITLE
Use threads for uploads

### PR DESCRIPTION
**Pull request by JanStevens**
Original implementation from  #284 

Updated based on the comments, for us we saw our CI going from 12min to 3min

By default it's disabled (and using the old logic)

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Thanks for PR
Can you please update it so that it looks like other boolean config like `include_manifest`?
YML support and stuff
Also need test case

**Comment by JanStevens** [comment]
Ping small friendly reminder if you got the time :)

**Comment by PikachuEXE** [comment]
Oh ya new commits won't trigger a notification on GitHub usually
Anyway will take a look tomorrow or later this week

**Comment by PikachuEXE** [comment]
And released in `2.9.0`

**Pull request merged**
