### PR TITLE
Download assets

### PR DESCRIPTION
**Pull request by devchick**
I added a feature to download manifest and asset files from a synced cloud storage.

The feature enables deploying same manifest and asset files to redundant servers without commiting them to their repository.

I suppose deployment operations as belows.

1. run assets:precompile rake task on local PC with `include_manifest` config option. It will upload a manifest file, not only asset files.
2. deploy rails appliation to servers without restart them.
3. run assets:sync:download rake task on the servers. It will download the manifest file and the asset files.
4. restart the rails applications
5. we are happy!

### CODE REVIEW

**Comment by PikachuEXE** [comment]
I doubt this feature is out of the responsibility for asset sync

Let's see what @davidjrice thinks

**Comment by devchick** [comment]
oh... really?

OK, I will create another gem like "asset_sync_download".

But, could you accept `include_manifest` feature?

**Comment by PikachuEXE** [comment]
Create another PR with `include_manifest` changes only first?

**Comment by devchick** [comment]
I divide this pull request to #365 and #366.

**Comment by devchick** [comment]
[fyi] I created new gem `asset_sync_download`

https://github.com/devchick/asset_sync_download

**Comment by PikachuEXE** [comment]
Gonna release tomorrow if no more changed required

**Comment by PikachuEXE** [comment]
`2.4.0` released!

**Pull request closed without merging**
