### PR TITLE
Notify of Fog changes in README

### PR DESCRIPTION
**Pull request by plribeiro3000**
This should close fog/fog-aws#83.

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@davidjrice What do we miss to get this merged?

**Comment by wnkz** [comment]
:+1:

**Comment by anark** [comment]
Unfortunately even with this change asset_sync still includes all of fog in your app since fog is a dev dependency

**Comment by PikachuEXE** [comment]
`2.0.0` released
Have a try!

**Comment by plribeiro3000** [comment]
Do wes

**Pull request closed without merging**
