### PR TITLE
Add Backblaze B2 Cloud Storage

### PR DESCRIPTION
**Pull request by duartemvix**
This should add support for Backblaze B2 Cloud Storage to Asset Sync

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Have you tested this with actual Backblaze B2?

**Comment by duartemvix** [comment]
> Have you tested this with actual Backblaze B2?

Yes, I did. I'm already using it in my other repositories linkng to my own fork. This one on this PR.

**Comment by PikachuEXE** [comment]
There are some failed jobs if you look into Travis
Can you fix it?

**Comment by duartemvix** [comment]
> There are some failed jobs if you look into Travis
> Can you fix it?

At Travis, apparently it's failing on old Ruby versions. And as far as I've seen it I'm not sure what is really wrong. I can't seem to understand Coveralls too.

**Comment by PikachuEXE** [comment]
I think it's due to the double created not stubbing all the method calls
https://github.com/AssetSync/asset_sync/blob/cc9d971f1288c851720e9c407e5152bc29b4b214/spec/unit/storage_spec.rb#L415-L442
In this case your updated code calls a new method `backblaze?` which is not stubbed
Adding a line in that test case like
```ruby
allow(config).to receive(:backblaze?).and_return(false)
```
should fix it

**Comment by duartemvix** [comment]
> I think it's due to the double created not stubbing all the method calls
> https://github.com/AssetSync/asset_sync/blob/cc9d971f1288c851720e9c407e5152bc29b4b214/spec/unit/storage_spec.rb#L415-L442
> 
> 
> In this case your updated code calls a new method `backblaze?` which is not stubbed
> Adding a line in that test case like
> ```ruby
> allow(config).to receive(:backblaze?).and_return(false)
> ```
> 
> should fix it

I missed that file. You're right, I'll push new changes right about now.

**Comment by duartemvix** [comment]
@PikachuEXE Have any idea on how to fix tests that failed running on jruby?

**Comment by PikachuEXE** [comment]
Don't worry
The "error" is
> The job exceeded the maximum time limit for jobs, and has been terminated.

I will just ignore jruby result, probably all passed
And this "error" is probably TravisCI issue

Merging next week otherwise I will forget to release (Too lazy to bring up my Mac on weekend...)

**Comment by duartemvix** [comment]
> Don't worry
> The "error" is
> 
> > The job exceeded the maximum time limit for jobs, and has been terminated.
> 
> I will just ignore jruby result, probably all passed
> And this "error" is probably TravisCI issue
> 
> Merging next week otherwise I will forget to release (Too lazy to bring up my Mac on weekend...)

Oh, okay! Great! Happy to help!

I'm also pushing some changes to the fog/fog-backblaze which in turn will make it more equal to its sisters fog-aws and fog-azurerm. That library needs some updates too but this PR should make master work at a basic level with Backblaze B2.

**Comment by PikachuEXE** [comment]
> I'm also pushing some changes to the fog/fog-backblaze

I am interested to know more

**Comment by PikachuEXE** [comment]
Released in `2.13.0`

**Pull request merged**
