### PR TITLE
Add some AWS options

### PR DESCRIPTION
**Pull request by abourquin**

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Maybe add default value for `fog_scheme` to doc and comment?
Just like `aws_signature_version`

**Comment by abourquin** [comment]
It is done ;)

**Comment by PikachuEXE** [comment]
Thanks :)

**Comment by PikachuEXE** [comment]
I found I missed some mistakes and fixed them on `master`
Can you try to check again and see if anything is missing?
https://github.com/AssetSync/asset_sync/commits/master

One day I will remove the generators and just put example config file on README
Or the other way around
So no one need to update both readme and generator templates when adding new options

**Comment by PikachuEXE** [comment]
@abourquin LOL I assumed your reaction means It's ok
Reaction won't send me notification by email btw
Better just reply next time (I just happen to check this thread again)

Will release next week

**Comment by PikachuEXE** [comment]
`2.3.0` Release!

**Pull request merged**
