### PR TITLE
Add support for webpacker assets

### PR DESCRIPTION
**Pull request by zinkkrysty**
Webpacker and react are [becoming part of Rails in 5.1](http://edgeguides.rubyonrails.org/5_1_release_notes.html#optional-webpack-support).

This PR is adding support for the assets generated by webpacker when running `assets:precompile` task. We are rolling this branch out in production soon, and hope that you can also use this in the main repository. What do you think about it?

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Thanks for the PR
1. Got some merge conflicts (since I merged #342)
2. I think it's better to rename the new options to `include_webpacker_assets`  
  Since `webpacker_assets` sound like an object/array for config
3. Is there some doc about the webpacker API?
I want to make sure we are using it properly

**Comment by zinkkrysty** [comment]
@PikachuEXE thanks for review. I solved the merge conflicts and renamed the option. 

Regarding the API, https://github.com/rails/webpacker is still a young repo, therefore not having a clear outlined API. However, I am also stating in the readme that this flag is experimental, therefore it might require some changes once the project matures. I will keep an eye on it and make another PR whenever it might change.

**Comment by PikachuEXE** [comment]
I think it's more flexible allow gem user to add file/folder paths at runtime
Then this gem don't need to know anything about webpacker or whatever gems

**Comment by PikachuEXE** [comment]
Please see #346 for potential alternative

**Comment by PikachuEXE** [comment]
Closing since #347 merged

**Pull request closed without merging**
