### PR TITLE
Feature/fog aws

### PR DESCRIPTION
**Pull request by j15e**
This a a follow-up of #295 working with the latest fog-aws. cc @eljojo

I have being using this for more than a month on a large deployment without issue.

### CODE REVIEW

**Comment by tricknotes** [comment]
It works for me :+1:

**Comment by driv3r** [comment]
it would be way better to go with `fog-core` which is provider agnostic

**Comment by woodhull** [comment]
Can one of these be merged? Why not? This requirement on all of fog annoys me.

**Comment by PikachuEXE** [comment]
This *might* be considered as breaking
So I will let @davidjrice decide

**Comment by PikachuEXE** [comment]
`2.0.0` released
Have a try!

**Comment by j15e** [comment]
Fixed by #336

**Pull request closed without merging**
