### PR TITLE
Add option additional_local_file_paths_proc

### PR DESCRIPTION
**Pull request by PikachuEXE**
To allow more files to be uploaded
Use Webpacker or whatever

### CODE REVIEW

**Comment by cawabunga** [comment]
What is the proper usage of that? Is something like:
`config.additional_local_file_paths_proc = -> { Dir.glob("public/packs/**/*") }`

**Comment by PikachuEXE** [comment]
Sorry for no including a details description
Let me explain a bit here and update the PR description later

This option ONLY allow users to add an additional list of file paths to be uploaded
(unless they are ignored)
The existing list of file paths generated by either
- directory searching (`config.manifest = false`)
- Use the Rails generated 'manifest.yml' file (`config.manifest = true`) 
is NOT affected

**Comment by PikachuEXE** [comment]
Also I think it might be better to allow user to add procs
But I will try to propose that design in another PR

**Comment by PikachuEXE** [comment]
Maybe #347 is better since it allow multiple lists to be added

**Comment by PikachuEXE** [comment]
CLosing since #347 merged

**Pull request closed without merging**
