### PR TITLE
Add AWS IAM to build-in initializer

### PR DESCRIPTION
**Pull request by bronislav**
This fix is required to improve configuration with environment variables.

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Do we any places that document the environment variables we support?

**Comment by bronislav** [comment]
@PikachuEXE most available options documented in the README, but this one I've foud in the source.

**Comment by PikachuEXE** [comment]
I can see `AWS_REDUCED_REDUNDANCY` is not documented
But I guess that's another issue

Can you update README to mention this new supported env var `AWS_IAM_ROLES`?

**Comment by bronislav** [comment]
Sure.

**Comment by PikachuEXE** [comment]
Let me know when it's done
New commits do not trigger any notification

**Pull request closed without merging**
