### PR TITLE
Close file handle after uploading

### LINKED ISSUE #348: "Too many open files" when having a lot of assets (files are opened but not closed)
We ran into this error on our server after precompilation of assets:

```
Excon::Error::Socket: Too many open files - getaddrinfo (Errno::EMFILE)
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/socket.rb:101:in `getaddrinfo’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/socket.rb:101:in `connect’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/ssl_socket.rb:153:in `connect’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/socket.rb:29:in `initialize’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/ssl_socket.rb:9:in `initialize’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:403:in `new’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:403:in `socket’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:100:in `request_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/mock.rb:48:in `request_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:16:in `request_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:16:in `request_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:16:in `request_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:249:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/idempotent.rb:27:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:272:in `rescue in request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:215:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/idempotent.rb:27:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:272:in `rescue in request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:215:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/idempotent.rb:27:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:272:in `rescue in request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:215:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-core-1.43.0/lib/fog/core/connection.rb:81:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:9:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-aws-1.2.1/lib/fog/aws/storage.rb:612:in `_request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-aws-1.2.1/lib/fog/aws/storage.rb:607:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-aws-1.2.1/lib/fog/aws/requests/storage/put_object.rb:47:in `put_object’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-aws-1.2.1/lib/fog/aws/models/storage/file.rb:219:in `save’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-core-1.43.0/lib/fog/core/collection.rb:51:in `create’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/storage.rb:208:in `upload_file’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/storage.rb:221:in `block in upload_files’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/storage.rb:219:in `each’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/storage.rb:219:in `upload_files’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/storage.rb:235:in `sync’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/asset_sync.rb:29:in `block in sync’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/asset_sync.rb:51:in `with_config’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/asset_sync.rb:28:in `sync’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/tasks/asset_sync.rake:5:in `block (2 levels) in <top (required)>'
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/tasks/asset_sync.rake:29:in `block in <top (required)>'
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/webpacker-1.2/lib/tasks/webpacker/compile.rake:40:in `block in <top (required)>'
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/deployer/.rbenv/versions/2.4.0/bin/bundle:22:in `load’
/home/deployer/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
```

We investigated and realized that the process had opened more than 900 files around the moment the error surfaced.

We then looked at the code that uploaded each file and it seems that the files are opened but not closed:

https://github.com/AssetSync/asset_sync/blob/master/lib/asset_sync/storage.rb#L125

This is not good practice to open a bunch of files and not close them. Each file should be closed before opening the next one.

We managed to run `bundle exec rake 'assets:clean'` with a lower nr of assets to keep and then deployment worked again, however it is a matter of time until we increase the nr of assets so it reaches the max limit of files opened per process (1024).

### PR DESCRIPTION
**Pull request by zinkkrysty**
Fixes #348 

Not tested yet.

### CODE REVIEW

**Comment by PikachuEXE** [comment]
I think you forgot the gzip one
https://github.com/AutoUncle/asset_sync/blob/c7ec7a982d2dda98fb5318d126e9d83c4354a656/lib/asset_sync/storage.rb#L174

**Comment by zinkkrysty** [comment]
I made the change. We are using this in production now. Seems to work fine.

**Comment by PikachuEXE** [comment]
Thanks, will be releasing after running test, I can't setup travis build for this repo...

**Comment by PikachuEXE** [comment]
`2.2.0` released, please have a try
Remember to run test next time, fixed some outdated stubbing due to this change

**Pull request merged**
